# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 20:25
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(choices=[('CAMD', 'CAMD'), ('CCIS', 'CCIS'), ('COS', 'COS'), ('CSSH', 'CSSH'), ('BOUVE', 'BOUVE'), ('DMSB', 'DMSB'), ('COE', 'COE'), ('LAW', 'LAW'), ('CPS', 'CPS'), ('PROVOST', 'PROVOST')], default='NONE', max_length=7)),
                ('course_number', models.CharField(max_length=10, null=True)),
                ('CRN', models.CharField(max_length=5, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'only numbers allowed')])),
                ('section', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Faculty Member',
                'verbose_name_plural': 'Faculty Members',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Partner Organization', max_length=100, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('courses', models.ManyToManyField(to='submit_reports.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.ManyToManyField(to='submit_reports.Course')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teaching Assistant',
                'verbose_name_plural': 'Teaching Assistants',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grad_year', models.CharField(max_length=4, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'only numbers allowed')])),
                ('college', models.CharField(choices=[('CAMD', 'CAMD'), ('CCIS', 'CCIS'), ('COS', 'COS'), ('CSSH', 'CSSH'), ('BOUVE', 'BOUVE'), ('DMSB', 'DMSB'), ('COE', 'COE'), ('LAW', 'LAW'), ('CPS', 'CPS'), ('PROVOST', 'PROVOST')], default='NONE', max_length=7)),
                ('courses', models.ManyToManyField(related_name='students', to='submit_reports.Course')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubmitReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('start_date', models.DateField(default=None)),
                ('end_date', models.DateField(default=None)),
                ('start_time', models.TimeField(default=None)),
                ('end_time', models.TimeField(default=None)),
                ('service_type', models.CharField(choices=[('DIRECT_SERVICE', 'Direct Service'), ('TRAINING', 'Trainings & Orientations'), ('IND_RESEARCH', 'Individual Research & Planning'), ('TEAM_RESEARCH', 'Team Research & Planning')], default='default', max_length=14, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=8)),
                ('summary', models.CharField(blank=True, max_length=150, null=True)),
                ('courses', models.ManyToManyField(blank=True, to='submit_reports.Course')),
                ('partner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='submit_reports.Partner')),
                ('submitter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='submit_reports.Student')),
            ],
            options={
                'verbose_name': 'Submitted Time Sheet',
                'verbose_name_plural': 'Submitted Time Sheets',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='submit_reports.Faculty'),
        ),
    ]
