# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 19:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submit_reports', '0006_auto_20160326_1903'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submitreport',
            options={},
        ),
        migrations.RemoveField(
            model_name='submitreport',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='submitreport',
            name='start_date',
        ),
    ]
