# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 23:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit_reports', '0007_auto_20160326_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitreport',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='submitreport',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
