# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit_reports', '0008_auto_20160326_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='name',
            field=models.CharField(default='New Partner Organization', max_length=100, null=True),
        ),
    ]
