# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 02:05
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit_reports', '0010_course_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course',
            new_name='college',
        ),
        migrations.RemoveField(
            model_name='student',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
        migrations.AddField(
            model_name='course',
            name='CRN',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='course_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='grad_year',
            field=models.CharField(max_length=4, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'only numbers allowed')]),
        ),
    ]
