# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 04:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit_reports', '0012_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(to='submit_reports.Course'),
        ),
        migrations.AddField(
            model_name='submitreport',
            name='course',
            field=models.ManyToManyField(to='submit_reports.Course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='CRN',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'only numbers allowed')]),
        ),
        migrations.AlterField(
            model_name='course',
            name='college',
            field=models.CharField(choices=[('CAMD', 'CAMD'), ('CCIS', 'CCIS'), ('COS', 'COS'), ('CSSH', 'CSSH'), ('BOUVE', 'BOUVE'), ('DMSB', 'DMSB'), ('COE', 'COE'), ('LAW', 'LAW'), ('CPS', 'CPS'), ('PROVOST', 'PROVOST')], default='NONE', max_length=7),
        ),
    ]
