# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 05:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submit_reports', '0013_auto_20160327_0459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submitreport',
            old_name='course',
            new_name='courses',
        ),
    ]
