# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 17:50
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submit_reports', '0015_auto_20160327_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='CRN',
            field=models.CharField(max_length=5, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'only numbers allowed')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submitreport',
            name='submitter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='submit_reports.Student'),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together=set([('nuid', 'user')]),
        ),
    ]
