# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit_reports', '0017_auto_20160404_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitreport',
            name='first_name',
            field=models.CharField(default='Samuel', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submitreport',
            name='last_name',
            field=models.CharField(default='Vogel', max_length=30),
            preserve_default=False,
        ),
    ]
