# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 17:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submit_reports', '0018_auto_20160410_1721'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminstaff',
            options={'verbose_name': 'Administrator', 'verbose_name_plural': 'Administrators'},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name': 'Faculty Member', 'verbose_name_plural': 'Faculty Members'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'Teaching Assistant', 'verbose_name_plural': 'Teaching Assistants'},
        ),
        migrations.AlterModelOptions(
            name='submitreport',
            options={'verbose_name': 'Submitted Time Sheet', 'verbose_name_plural': 'Submitted Time Sheets'},
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(error_messages={'unique': 'This user is already associated with a student'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submitreport',
            name='service_type',
            field=models.CharField(choices=[('DIRECT_SERVICE', 'Direct Service'), ('TRAINING', 'Training'), ('IND_RESEARCH', 'Individual Research'), ('TEAM_RESEARCH', 'Team Research')], default='default', max_length=14, null=True),
        ),
    ]
