# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit_reports', '0018_auto_20160410_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitreport',
            name='service_type',
            field=models.CharField(choices=[('DIRECT_SERVICE', 'Direct Service'), ('TRAINING', 'Training'), ('IND_RESEARCH', 'Individual Research'), ('TEAM_RESEARCH', 'Team Research')], default='default', max_length=14, null=True),
        ),
    ]
