# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 20:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submit_reports', '0019_auto_20160411_1727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminstaff',
            options={'verbose_name': 'Administrator', 'verbose_name_plural': 'Administrators'},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name': 'Faculty Member', 'verbose_name_plural': 'Faculty Members'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'Teaching Assistant', 'verbose_name_plural': 'Teaching Assistants'},
        ),
        migrations.AlterModelOptions(
            name='submitreport',
            options={'verbose_name': 'Submitted Time Sheet', 'verbose_name_plural': 'Submitted Time Sheets'},
        ),
    ]
