# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit_reports', '0020_auto_20160411_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitreport',
            name='end_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='submitreport',
            name='start_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='submitreport',
            name='end_time',
            field=models.TimeField(default=None),
        ),
        migrations.AlterField(
            model_name='submitreport',
            name='start_time',
            field=models.TimeField(default=None),
        ),
    ]
