# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-17 17:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submit_reports', '0021_auto_20160413_0107'),
        ('submit_reports', '0019_auto_20160414_1716'),
    ]

    operations = [
    ]
