# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 15:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submit_reports', '0021_auto_20160413_0107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminstaff',
            name='user',
        ),
        migrations.DeleteModel(
            name='AdminStaff',
        ),
    ]
