# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submit_reports', '0022_auto_20160418_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='section',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='courses',
            field=models.ManyToManyField(to='submit_reports.Course'),
        ),
        migrations.AddField(
            model_name='student',
            name='college',
            field=models.CharField(choices=[('CAMD', 'CAMD'), ('CCIS', 'CCIS'), ('COS', 'COS'), ('CSSH', 'CSSH'), ('BOUVE', 'BOUVE'), ('DMSB', 'DMSB'), ('COE', 'COE'), ('LAW', 'LAW'), ('CPS', 'CPS'), ('PROVOST', 'PROVOST')], default='NONE', max_length=7),
        ),
        migrations.AddField(
            model_name='submitreport',
            name='partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='submit_reports.Partner'),
        ),
    ]
