# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-17 18:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submit_reports', '0022_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submitreport',
            name='service_type',
            field=models.CharField(choices=[('DIRECT_SERVICE', 'Direct Service'), ('TRAINING', 'Trainings & Orientations'), ('IND_RESEARCH', 'Individual Research & Planning'), ('TEAM_RESEARCH', 'Team Research & Planning')], default='default', max_length=14, null=True),
        ),
    ]
