# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit_reports', '0024_auto_20160418_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitreport',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, to='submit_reports.Course'),
        ),
    ]
