# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 19:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submit_reports', '0026_auto_20160418_1615'),
        ('submit_reports', '0023_auto_20160417_1812'),
    ]

    operations = [
    ]
